package com.canxue.basemb.entity;

import com.canxue.basemb.common.base.BaseEntity;
import lombok.Data;

import java.util.Date;
@Data
public class Book extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_no
     *
     * @mbggenerated
     */
    private Long bookNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.type_dec
     *
     * @mbggenerated
     */
    private String typeDec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.entry_date
     *
     * @mbggenerated
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    public Book(Long id, String bookName, Long bookNo, String author, Integer type, String typeDec, Date entryDate) {
        this.id = id;
        this.bookName = bookName;
        this.bookNo = bookNo;
        this.author = author;
        this.type = type;
        this.typeDec = typeDec;
        this.entryDate = entryDate;
    }


}