#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mb_plus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#指定mapper映射位置
mybatis:
  mapper-locations: classpath:xml/*.xml
  type-aliases-package: com.canxue.basemb.entity
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql

# Logger Config
logging:
  level:
    com.canxue.basemb: debug
    java.sql: debug
    org.apache.ibatis: info