package com.canxue.basemb.mapper;

import com.canxue.basemb.common.base.BaseMapper;
import com.canxue.basemb.entity.Book;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BookMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    @Update({
        "update  book set status = -1 ",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    @Insert({
        "insert into book (id, book_name, ",
        "book_no, author, type, ",
        "type_dec, entry_date)",
        "values (#{id,jdbcType=BIGINT}, #{bookName,jdbcType=VARCHAR}, ",
        "#{bookNo,jdbcType=BIGINT}, #{author,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{typeDec,jdbcType=VARCHAR}, #{entryDate,jdbcType=DATE})"
    })
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, book_name, book_no, author, type, type_dec, entry_date",
        "from book",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    @Update({
        "update book",
        "set book_name = #{bookName,jdbcType=VARCHAR},",
          "book_no = #{bookNo,jdbcType=BIGINT},",
          "author = #{author,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "type_dec = #{typeDec,jdbcType=VARCHAR},",
          "entry_date = #{entryDate,jdbcType=DATE}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Book record);
}